---
- name: Update The Operating System
  apt:
    update_cache: yes

- name: Install cron
  apt:
    name: cron
    state: present

- name: Install system dependencies
  apt:
    name:
    - python3
    - python3-venv
    - libaugeas0
  become: true

- name: Check if file exists
  stat:
    path: /opt/certbot/bin/certbot
  register: certbot_check

- name: Set up a Python virtual environment
  command: "{{ item }}"
  with_items:
    - python3 -m venv /opt/certbot/
    - /opt/certbot/bin/pip install --upgrade pip
  become: true
  when: not certbot_check.stat.exists

- name: Install Certbot
  command: /opt/certbot/bin/pip install certbot certbot-nginx
  become: true
  when: not certbot_check.stat.exists

- name: Prepare the Certbot command
  file:
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: yes
  become: true

- import_tasks: certificate.yml
  when: domain_name is defined

- name: Config auto-renew cerbot
  cron:
    name: "renew certificate Certbot"
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    job: "certbot renew --quiet"