---
- name: Update package lists
  apt: 
    update_cache: yes

- name: Install system dependencies
  apt:
    name:
    - python3-pip
    - python3-pymysql
  become: true

- name: Download MySQL APT configuration package
  get_url:
    url: https://repo.mysql.com//mysql-apt-config_0.8.29-1_all.deb
    dest: /tmp/mysql-apt-config.deb
    mode: '0644'

- name: Install MySQL APT configuration package
  apt:
    deb: /tmp/mysql-apt-config.deb

- name: Update package lists again after MySQL repo is added
  apt: 
    update_cache: yes

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present 

- name: Update mysql password for root user
  community.mysql.mysql_user:
    # Update the superuser to have all grants and a password
    name: "root"
    host: localhost
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    # Login *as root* to perform this change, even though you might
    # be altering the root user itself
    login_user: root
    login_password: ""
    login_port: "3306"
    login_host: localhost
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    # As a good measure,have ansible check whether an implicit login
    # is possible first
    check_implicit_admin: yes

- name: Create dev database
  community.mysql.mysql_db:
    name: "{{ db_database }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create dev user with all privileges on dev database
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    host: "%"  # Allow access from any host
    password: "{{ db_password }}"
    priv: "{{ db_database }}.*:ALL"  # Grant all privileges on the database
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
