---
- name: Update APT package lists
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Check if user is in the Docker group
  command: "getent group docker | grep -w {{ ansible_env.SUDO_USER }}"
  register: docker_group_check
  ignore_errors: true

- name: Add user {{ ansible_env.SUDO_USER }} to docker group
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes
  when: docker_group_check.rc != 0

- name: Check if Docker Compose binary exists
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_check

- name: Download Docker Compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
  when: not docker_compose_check.stat.exists
